sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

dist: xenial

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: false
  include:
    - php: 7.1
      env: SYMFONY_VERSION='4.0.*'
    - php: 7.1
      env: SYMFONY_VERSION='4.1.*'
    - php: 7.1
      env: SYMFONY_VERSION='4.2.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.3.*'
    - php: 7.4
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.0.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.1.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.2.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.3.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.0.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.1.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.2.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.3.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.4
      env: SYMFONY_VERSION='4.0.*'
    - php: 7.4
      env: SYMFONY_VERSION='4.1.*'
    - php: 7.4
      env: SYMFONY_VERSION='4.2.*'
    - php: 7.4
      env: SYMFONY_VERSION='4.3.*'
    - php: 7.4
      env: SYMFONY_VERSION='4.4.*'

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
